version: '3.8'

services:
  frontend:
    image: httpd:latest
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    healthcheck:
      test: curl http://localhost:80 || exit 1
      interval: 40s
      timeout: 30s
      retries: 1
      start_period: 60s
    networks:
      - app-network


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
